version: '3.8'

services:
  db:
    image: mariadb
    container_name: DockerDB    
    restart: always
    environment:
      MYSQL_DATABASE: rest_with_asp_net
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: r00t
      MYSQL_PASSWORD: r00t
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
